name: J2MC_SeniorFun
main: to.joe.j2mc.seniorfun.J2MC_SeniorFun
version: 1.0
website: http://forums.joe.to
author: J2 Minecraft Plugin Team
description: Senior Fun module! (for ages 3 and up)
commands:
  kickall:
    description: Kicks all player for specified reason or generic reason if nothing specified
    usage: |
            /kickall reason
  madagascar:
    description: Shut. Down. Everything.
    usage: |
            /madagascar
  say:
    description: Say something!
    usage: |
            /say message
  maintenance:
    description: Put the server into maintenance mode!
    usage: |
            /maintenance
  firealladmins:
    description: fire all admins
    usage: |
            /firealladmins
permissions:
  j2mc.senior:
    description: gives access to all the commands here
    default: op